---
- name: Set somaxcon
  sysctl:
    name: net.core.somaxconn
    value: 4096
    state: present

- name: Set tcp_fin_timeout
  sysctl:
    name: net.ipv4.tcp_fin_timeout
    value: 30
    state: present

- name: Set tcp_keepalive_intvl
  sysctl:
    name: net.ipv4.tcp_keepalive_intvl
    value: 30
    state: present

- name: Set tcp_keepalive_time
  sysctl:
    name: net.ipv4.tcp_keepalive_time
    value: 120
    state: present

- name: Set tcp_max_syn_backlog
  sysctl:
    name: net.ipv4.tcp_max_syn_backlog
    value: 4096
    state: present
