---
- name: Allocate a swap file
  command: fallocate -l {{ swapfile_size }} {{ swapfile_path }}
  args:
    creates: "{{ swapfile_path }}"
  register: file_allocated

- name: Change the swap file permissions
  file:
    path: "{{ swapfile_path }}"
    mode: 0600

- name: Format the swap file
  command: mkswap {{ swapfile_path }}
  when: file_allocated | changed

- name: Activate the swap file
  command: swapon {{ swapfile_path }}
  when: file_allocated | changed

- name: Mount the swap file
  lineinfile:
    dest: /etc/fstab
    line: "{{ swapfile_path }} none swap defaults 0 0"
    state: present

- name: Set swappiness
  sysctl:
    name: vm.swappiness
    value: 1
    state: present

- name: Set overcommit_memory
  sysctl:
    name: vm.overcommit_memory
    value: 2
    state: present
