---
- name: Remove unofficial docker
  dnf: name={{ item }} state=absent
  with_items:
    - docker
    - docker-common
    - container-selinux
    - docker-selinux
    - docker-engine

- name: Remove old docker repo
  yum_repository:
    name: docker-main
    state: absent

- name: Add official docker repository
  yum_repository:
    name: docker-ce-stable
    description: Docker Repository
    baseurl: https://download.docker.com/linux/fedora/$releasever/$basearch/stable
    enabled: yes
    gpgcheck: yes
    gpgkey: https://download.docker.com/linux/fedora/gpg

- name: Install Docker
  dnf:
    name: docker-ce
    state: latest

- name: Copy daemon.json
  copy:
    src: daemon.json
    dest: /etc/docker/
  notify:
    - restart docker

- name: Create a user for the docker user namespace remapping
  user:
    name: dockremap
    shell: /usr/sbin/nologin
    createhome: no
    comment: Account used by docker to remap users in containers
    system: yes

- name: Add the "{{ ansible_user }}" user to the "docker" group
  user:
    name: "{{ ansible_user }}"
    groups: docker

- name: Make sure Docker is running and enabled
  service:
    name: docker
    state: started
    enabled: true
