---
- name: Ensure /etc/systemd/system.conf.d/ exists
  file:
    path: /etc/systemd/system.conf.d/
    state: directory

- name: Set limits
  copy:
    src: limits.conf
    dest: /etc/systemd/system.conf.d/
